#!/bin/bash

set -e

PG_FOLDER=dirname `find -L /var/vcap/jobs/db-backup -name pg_restore -print`

PATH=/var/vcap/packages/postgres-unknown/bin:/var/vcap/packages/postgresql_9.3/bin:$PG_FOLDER:$PATH

pg_restore --user=atc --format=custom --schema=public --clean --dbname=atc $BBR_ARTIFACT_DIRECTORY/atc.backup 
